### ISSUE TITLE
Cannot convert value of type `string` to integer

### ISSUE THREAD

**Issue by roester** [UseMuffin/Obfuscate#17]
I just added the Obfuscate behavior but I think I'm missing something. When I try to find a model with a cloaked id, I get the error message `Cannot convert value of type `string` to integer`

I pretty much followed the instructions. This is the code in my table. Will be called after a simple find in the the view method of my controller.
 
```php
    public function beforeFind($event, Query $query, $options, $primary)
    {
        return $query->find('obfuscate');
    }
```

The problem is, that the beforeFind event of the table is called after the beforeFind event of the behavior so the cloaked id (string) won't be uncloaked when I add the 'obfuscate' finder in the table's beforeFind. I think this could be solved by altering the behavior and model callback priorities, but since this is not mentioned in the instructions and doesn't really feel right, I thought there might be a different solution?

**Comment by ADmad** [comment]
Readme updated.
