### ISSUE TITLE
Baked ORM rules checker `existsIn` fails looking up non-obfuscated id

### ISSUE THREAD

**Issue by bravo-kernel** [UseMuffin/Obfuscate#7]
Now that I have added the ObfuscateBehavior to my UsersTable the following (baked) ORM rules checker in my UserProfilesTable no longer passes:

``` php
public function buildRules(RulesChecker $rules)
{
    $rules->add($rules->existsIn(['user_id'], 'Users'));
}
```

Pretty explainable if you ask me since the rules checker is passing the elucidated/real id whereas the UsersTable is expecting the obfuscated one.

Now for the question; what would be the advised way to solve this? I'm thinking about creating a custom rules checker that obfuscates the id myself.

**Comment by jadb** [comment]
Interesting... I will try replicating, shouldn't be too hard.

**Comment by bravo-kernel** [comment]
Is this solution as suggested in #muffin acceptable? If so I will make an attempt.

```
(3:15:05 PM) marlinc: I haven't really checked the Obfuscate plugin but wouldn't the same issue occur when doing a ->get();?
(3:15:47 PM) marlinc: If that's the case wouldn't it be a better idea to specifically tell the Obfuscate plugin to do its job when you for example pass 'obfuscate' => true in the options?
(3:16:36 PM) marlinc: That way you're still able to do regular lookups in code and rather create exceptions when you know a user is accessing the data
(3:20:16 PM) stillnoob: marlinc: that sure makes sense to me
(3:28:10 PM) marlinc: :)
(3:28:33 PM) stillnoob: not the slightest clue on how to implemented but hey haha :P
(3:31:22 PM) marlinc: https://github.com/UseMuffin/Obfuscate/blob/master/src/Model/Behavior/ObfuscateBehavior.php#L95-L109
(3:31:28 PM) marlinc: It shoudn't be that difficult
(3:31:44 PM) marlinc: You can get the options passed by doing something like $query->getOptions
(3:32:02 PM) marlinc: You then check if 'obfuscate' is set to true and that should be it
```

**Comment by ADmad** [comment]
Given the problems it's causing it would be better to have the obfuscation/elucidation out-in instead of opt-out. Then for anyone who needs it on all find calls, we can state in docs how to setup the beforeFind callback.

**Comment by bravo-kernel** [comment]
@ADmad could the above `out-in` a typo?

**Comment by ADmad** [comment]
Yes, I meant opt-in :)

**Comment by bravo-kernel** [comment]
PR open #8
